Worked around error C2572: 'std::enable_if': redefinition of default argument: parameter 1
All std C++ headers are hidden and replaced with import std.
Some std C headers are added.

Cfr. https://developercommunity.visualstudio.com/t/VS2022-175-Preview-3---Compiler-bug-wit/10256508