Worked around error C2039: 'vformat': is not a member of 'fmt'
This error is present upon building fmt as a static library with C++ modules.
This error is not present upon building fmt as a static library without C++ modules.
This workaround should not be needed due to the "missing" member being declared right before this use.